# Generated by Django 5.2.6 on 2025-10-18 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GPSTrack",
            fields=[
                ("track_id", models.AutoField(primary_key=True, serialize=False)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "total_distance_miles",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                ("text_gps_data", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gps_tracks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gps_tracks",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="GPSPoint",
            fields=[
                ("point_id", models.AutoField(primary_key=True, serialize=False)),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                (
                    "altitude_feet",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "accuracy_feet",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "speed_mps",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("recorded_at", models.DateTimeField()),
                ("point_order", models.IntegerField()),
                (
                    "track",
                    models.ForeignKey(
                        db_column="track_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gps_points",
                        to="tracking.gpstrack",
                    ),
                ),
            ],
            options={
                "db_table": "gps_points",
                "ordering": ["track", "point_order"],
            },
        ),
        migrations.CreateModel(
            name="Hike",
            fields=[
                ("hike_id", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("duration_min", models.IntegerField(blank=True, null=True)),
                (
                    "distance_miles",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "weather_conditions",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trail",
                    models.ForeignKey(
                        db_column="trail_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hikes",
                        to="users.trail",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hikes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hikes",
                "ordering": ["-start_time"],
            },
        ),
        migrations.AddField(
            model_name="gpstrack",
            name="hike",
            field=models.ForeignKey(
                db_column="hike_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gps_tracks",
                to="tracking.hike",
            ),
        ),
    ]
