# Generated by Django 5.2.6 on 2025-10-24 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tracking", "0001_initial"),
        ("trails", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gpstrack",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gps_tracks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gpspoint",
            name="track",
            field=models.ForeignKey(
                db_column="track_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gps_points",
                to="tracking.gpstrack",
            ),
        ),
        migrations.AddField(
            model_name="hike",
            name="trail",
            field=models.ForeignKey(
                db_column="trail_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hikes",
                to="trails.trail",
            ),
        ),
        migrations.AddField(
            model_name="hike",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hikes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gpstrack",
            name="hike",
            field=models.ForeignKey(
                db_column="hike_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gps_tracks",
                to="tracking.hike",
            ),
        ),
    ]
