# Generated by Django 5.2.6 on 2025-10-24 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("forums", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="forumpost",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forum_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="forumthread",
            name="category",
            field=models.ForeignKey(
                db_column="category_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forum_threads",
                to="forums.forumcategory",
            ),
        ),
        migrations.AddField(
            model_name="forumthread",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thread_author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="forumpost",
            name="thread",
            field=models.ForeignKey(
                db_column="thread_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="forums.forumthread",
            ),
        ),
    ]
