# Generated by Django 5.2.6 on 2025-12-04 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forums", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumPostPhoto",
            fields=[
                ("photo_id", models.AutoField(primary_key=True, serialize=False)),
                ("photo_url", models.URLField(max_length=500)),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        db_column="post_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="forums.forumpost",
                    ),
                ),
            ],
            options={
                "db_table": "forum_post_photos",
                "ordering": ["uploaded_at"],
            },
        ),
    ]
