# Generated by Django 5.2.6 on 2025-12-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forums", "0003_forumpostphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumpost",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
