# Generated by Django 5.2.6 on 2025-10-24 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("trails", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="user",
            field=models.ForeignKey(
                db_column="int_user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                db_column="int_user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="savedtrail",
            name="user",
            field=models.ForeignKey(
                db_column="int_user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_trails",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trail",
            name="park",
            field=models.ForeignKey(
                db_column="park_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trails",
                to="trails.park",
            ),
        ),
        migrations.AddField(
            model_name="savedtrail",
            name="trail",
            field=models.ForeignKey(
                db_column="int_trail_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_by_users",
                to="trails.trail",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="trail",
            field=models.ForeignKey(
                db_column="int_trail_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="trails.trail",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="trail",
            field=models.ForeignKey(
                blank=True,
                db_column="int_trail_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="trails.trail",
            ),
        ),
        migrations.AddField(
            model_name="trailcondition",
            name="trail",
            field=models.ForeignKey(
                db_column="int_trail_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conditions",
                to="trails.trail",
            ),
        ),
        migrations.AddField(
            model_name="trailcondition",
            name="user",
            field=models.ForeignKey(
                db_column="int_user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trail_conditions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trailfeature",
            name="trail",
            field=models.ForeignKey(
                db_column="int_trail_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="features",
                to="trails.trail",
            ),
        ),
        migrations.AddField(
            model_name="trailtag",
            name="tag",
            field=models.ForeignKey(
                db_column="int_tag_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trail_tags",
                to="trails.tag",
            ),
        ),
        migrations.AddField(
            model_name="trailtag",
            name="trail",
            field=models.ForeignKey(
                db_column="int_trail_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trail_tags",
                to="trails.trail",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="savedtrail",
            unique_together={("user", "trail")},
        ),
        migrations.AlterUniqueTogether(
            name="trailtag",
            unique_together={("trail", "tag")},
        ),
    ]
